baseURL: "https://plaenkler.com"
languageCode: "en-us"
title: "Plaenkler's blog"
theme: "GitHub-Style-Plaenkler"
params:
  author: "Simon Lukas"
  description: "System integrator with a great interest in software and hardware development. Currently employed by Avanis GmbH and managing director of LaKiS GbR."
  avatar: "images/simon-lukas.png"
  github: "Plaenkler"
  email: "info@plaenkler.com"
  url: "https://plaenkler.com"
  keywords: "blog"
  rss: true
  lastmod: true
  favicon: "/images/github.png"
  location: "Germany"
  userStatusEmoji: "😀"
