baseURL: "https://plaenkler.com"
languageCode: "en-us"
title: "Programming Insights and Tips from Plaenkler's Blog"
theme: "GitHub-Style-Plaenkler"
googleAnalytics: "G-1HP5PN4E3Q"

params:
  author: "Simon Lukas"
  description: "System integrator with a great interest in software and hardware development. Currently employed by Avanis GmbH and managing director of LaKiS GbR."
  avatar: "/images/simon-lukas.png"
  github: "Plaenkler"
  email: "info@plaenkler.com"
  url: "https://plaenkler.com"
  keywords: "Coding tutorials, Web development, Best practices"
  rss: true
  lastmod: true
  favicon: "/images/github.png"
  location: "Germany"
  userStatusEmoji: "😀"
