# baseURL: "https://Plaenkler.com/"
baseURL: "https://plaenkler.github.io/Blog/"
languageCode: "de-de"
title: "Plaenkler's blog"
theme: "GitHub-Style-Plaenkler"
params:
  author: "Simon Lukas"
  description: "System integrator with a great interest in software and hardware development."
  avatar: "images/plaenkler.png"
  github: "Plaenkler"
  email: "info@plaenkler.com"
  url: "https://plaenkler.com"
  keywords: "blog"
  rss: true
  lastmod: true
  favicon: "/images/github.png"
  location: "Germany"
  userStatusEmoji: "😀"
