baseURL = "https://Plaenkler.com/"
languageCode = "en-us"
title = "Plaenkler's blog"
theme = "GitHub-Style-Plaenkler"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Plaenkler"
  description = "No cookies."
  github = "Plaenkler"
  facebook = "Plaenkler"
  twitter = "Plaenkler"
  linkedin = "Plaenkler"
  instagram = "Plaenkler"
  tumblr = "Plaenkler"
  email = "plaenkler@gmail.com"
  url = "https://plaenkler.com"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  favicon = "/images/github.png"
  location = "Germany"
  userStatusEmoji = "😀"
  enableGitalk = true
    
  [params.gitalk]
    clientID = "Your client ID"
    clientSecret = "Your client secret"
    repo = "Plaenkler"
    owner = "Plaenkler"
    admin = "Plaenkler"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token"
  [[params.links]]
    title = "Link"
    href = "https://github.com/plaenkler"
  [[params.links]]
    title = "Link2"
    href = "https://plaenkler.com"
    icon = "https://plaenkler.com/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
