name = "GitHub-Style-Plaenkler"
license = "BSD-3-Clause"
licenselink = "https://github.com/Plaenkler/Blog/blob/main/LICENSE"
description = "A hugo theme that looks like GitHub"
homepage = "https://github.com/Plaenkler"
tags = ["blog", "google analytics"]
features = ["google analytics"]
min_version = "0.41"

[author]
  name = "Plaenkler"
  homepage = "https://github.com/Plaenkler"
